import type { CaseStudy } from "@/types/content";

export const caseStudies: CaseStudy[] = [
  {
    slug: "la-maison-istanbul",
    title: "Fine dining deneyimi, dijital vitrin",
    client: "La Maison İstanbul",
    sector: "Gastronomi",
    projectType: "Kurumsal Web",
    scope: "Web + UX + SEO",
    services: ["Web Tasarım", "UX", "SEO"],
    excerpt:
      "Rezervasyon odaklı lüks restoran sitesi — editoryal tipografi, sinematik görsel dil ve mobil-first akış.",
    caseNote: "Lansman sonrası 3 ayda rezervasyon hunisi yeniden kurgulandı.",
    preview: "website",
    layout: "featured",
    year: "2025",
    metric: { label: "Rezervasyon artışı", value: "+68%" },
    theme: { accent: "#c9a962", surface: "#12100e" },
  },
  {
    slug: "aquaflow-premium",
    title: "Kurumsal kimlik, premium algı",
    client: "AquaFlow",
    sector: "Endüstriyel Hizmet",
    projectType: "Marka Kimliği",
    scope: "Kimlik + Kurumsal + Araç",
    services: ["Marka Kimliği", "Kurumsal Tasarım"],
    excerpt:
      "Vidanjör ve altyapı hizmetleri için güven veren, premium bir marka dünyası — araç giydirme dahil.",
    caseNote: "B2B teklif sürecinde marka güveni önceliklendirildi.",
    preview: "branding",
    layout: "tall",
    year: "2025",
    metric: { label: "Marka hatırlanırlığı", value: "3.2×" },
    theme: { accent: "#3d8bfd", surface: "#0a1018" },
  },
  {
    slug: "moda-atelier-social",
    title: "Sezon lansmanı, sosyal kampanya",
    client: "Moda Atelier",
    sector: "Moda & Perakende",
    projectType: "Sosyal Kampanya",
    scope: "Instagram + Reels + İçerik",
    services: ["Sosyal Medya", "İçerik Üretimi"],
    excerpt:
      "Lookbook estetiğinde Instagram ve Reels serisi — editorial grid, tutarlı filtre ve hikâye akışı.",
    caseNote: "Sezon lansmanı 6 haftalık içerik takvimiyle yönetildi.",
    preview: "social",
    layout: "tall",
    year: "2024",
    metric: { label: "Etkileşim oranı", value: "+142%" },
    theme: { accent: "#e8d4c4", surface: "#141210" },
  },
  {
    slug: "verde-market",
    title: "Dönüşüm odaklı e-ticaret vitrini",
    client: "Verde Market",
    sector: "E-Ticaret",
    projectType: "Landing & CRO",
    scope: "Landing + Mobil + CRO",
    services: ["Landing Page", "CRO", "Performans"],
    excerpt:
      "Organik ürün kataloğu için hızlı, güven veren landing — net CTA hiyerarşisi ve sepete giden kısa yol.",
    caseNote: "Sepet terk oranı A/B testleriyle optimize edildi.",
    preview: "device",
    layout: "wide",
    year: "2025",
    metric: { label: "Dönüşüm oranı", value: "+41%" },
    theme: { accent: "#5cb87a", surface: "#0c120e" },
  },
  {
    slug: "teknikplus-ads",
    title: "Google Ads performans paneli",
    client: "TeknikPlus",
    sector: "B2B Hizmet",
    projectType: "Performans Reklam",
    scope: "Google Ads + Analytics",
    services: ["Google Ads", "Analytics", "Raporlama"],
    excerpt:
      "Çok kanallı kampanya yönetimi — ROAS, dönüşüm hunisi ve bütçe optimizasyonu tek bakışta.",
    caseNote: "Aylık performans raporu ve bütçe revizyonu dahil.",
    preview: "dashboard",
    layout: "compact",
    year: "2025",
    metric: { label: "ROAS", value: "4.8×" },
    theme: { accent: "#4d8fff", surface: "#0a0e14" },
  },
  {
    slug: "skyline-drone",
    title: "Havadan çekim, marka sunumu",
    client: "Skyline İnşaat",
    sector: "İnşaat & Gayrimenkul",
    projectType: "Video & Sunum",
    scope: "Drone + Lansman Sunumu",
    services: ["Video Prodüksiyon", "Sunum Tasarımı"],
    excerpt:
      "Proje lansmanı için sinematik drone çekimi ve fullscreen sunum deneyimi — satış ofisi vitrini.",
    caseNote: "Satış ofisi dijital vitrin ile senkron yayınlandı.",
    preview: "ads",
    layout: "compact",
    year: "2024",
    metric: { label: "Lead artışı", value: "+53%" },
    theme: { accent: "#7eb8ff", surface: "#0e1014" },
  },
];
